# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Homete < Formula
  desc "Praise you."
  homepage ""
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sho-jp/homete/releases/download/v0.0.4/homete_0.0.4_Darwin_x86_64.tar.gz"
      sha256 "784acbe2c31e5ec4319274a99cb120872e18d26a1d71a0cd2c7d9c6399aa5030"

      def install
        bin.install "homete"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sho-jp/homete/releases/download/v0.0.4/homete_0.0.4_Darwin_arm64.tar.gz"
      sha256 "1f9a5c4224d2333fa093760d3c720afca087799b9604cc0bcb21d62ad2c526b6"

      def install
        bin.install "homete"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sho-jp/homete/releases/download/v0.0.4/homete_0.0.4_Linux_x86_64.tar.gz"
      sha256 "d9b4eba51c6fff6f941a2a29969378d34e88a790dda3e7c18a952f80bb7dd77d"

      def install
        bin.install "homete"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sho-jp/homete/releases/download/v0.0.4/homete_0.0.4_Linux_arm64.tar.gz"
      sha256 "8729cc9abd67b089e24ef6759d3e448a42ac26fb3919e1971f103c7001b3faa7"

      def install
        bin.install "homete"
      end
    end
  end

  test do
    system "#{bin}/homete help"
  end
end
