# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Homete < Formula
  desc "Praise you."
  homepage ""
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sho-jp/homete/releases/download/v1.0.0/homete_1.0.0_Darwin_arm64.tar.gz"
      sha256 "e89760161536b3ccadc41e292549f9e4c9bcfb9d0f89ff5f150f4aad217993f4"

      def install
        bin.install "homete"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sho-jp/homete/releases/download/v1.0.0/homete_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "94d118d802037086911f18b00b6058859680474f18b3825a889285f47784d2c5"

      def install
        bin.install "homete"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sho-jp/homete/releases/download/v1.0.0/homete_1.0.0_Linux_x86_64.tar.gz"
      sha256 "6455074cf7c9df88416bf0c94703d9b450f6d4cfe1049eca1b30eeea12797967"

      def install
        bin.install "homete"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sho-jp/homete/releases/download/v1.0.0/homete_1.0.0_Linux_arm64.tar.gz"
      sha256 "abff72e1f6815a8701c468c07eef4b3616340e3b9290690d33c06405dac3e7e2"

      def install
        bin.install "homete"
      end
    end
  end

  test do
    system "#{bin}/homete help"
  end
end
