# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Homete < Formula
  desc "Praise you."
  homepage ""
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sho-jp/homete/releases/download/v1.0.0/homete_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "6a550effe51bca0146a5b700fef78c39cedd6ceda5637b646b9bf44f3e6e42e5"

      def install
        bin.install "homete"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sho-jp/homete/releases/download/v1.0.0/homete_1.0.0_Darwin_arm64.tar.gz"
      sha256 "8d1b51e5f9e6d445ae4a211447dd2091750c92fb34dfda8712f1de286cf10fa9"

      def install
        bin.install "homete"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sho-jp/homete/releases/download/v1.0.0/homete_1.0.0_Linux_arm64.tar.gz"
      sha256 "aecab90f83ed9a549736cbad0b1e838d7c67c1f0bdc460c1560680e28ecae00b"

      def install
        bin.install "homete"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sho-jp/homete/releases/download/v1.0.0/homete_1.0.0_Linux_x86_64.tar.gz"
      sha256 "a129cb75209d21c9c3d5f26660c424f3eef7db328fc7ca25065e44ab7760c457"

      def install
        bin.install "homete"
      end
    end
  end

  test do
    system "#{bin}/homete help"
  end
end
